// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workiy_360.EntityFramework.Context;

#nullable disable

namespace Workiy_360.EntityFramework.Migrations
{
    [DbContext(typeof(Workiy360DbContext))]
    [Migration("20240812172841_UpdateDateOnly")]
    partial class UpdateDateOnly
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");

            modelBuilder.Entity("Workiy_360.EntityFramework.ContactType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("TYPE_ID");

                    b.Property<string>("TypeName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("TYPE_NAME");

                    b.HasKey("TypeId")
                        .HasName("PRIMARY");

                    b.ToTable("contact_type", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeAdditionalInfo", b =>
                {
                    b.Property<int>("AddInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADD_INFO_ID");

                    b.Property<string>("AddGroupLink")
                        .HasColumnType("text")
                        .HasColumnName("ADD_GROUP_LINK");

                    b.Property<string>("AddGroupName")
                        .HasColumnType("text")
                        .HasColumnName("ADD_GROUP_NAME");

                    b.Property<string>("AddGroupType")
                        .HasColumnType("text")
                        .HasColumnName("ADD_GROUP_TYPE");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("AddInfoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID");

                    b.ToTable("employee_additional_info", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeAddressDetail", b =>
                {
                    b.Property<int>("AddressPkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADDRESS_PK_ID");

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS_1");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS_2");

                    b.Property<string>("AddressType")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("ADDRESS_TYPE");

                    b.Property<string>("Area")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("AREA");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CITY");

                    b.Property<int?>("ContactFkId")
                        .HasColumnType("int")
                        .HasColumnName("CONTACT_FK_ID");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("COUNTRY");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<int?>("Pincode")
                        .HasColumnType("int")
                        .HasColumnName("PINCODE");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("STATE");

                    b.HasKey("AddressPkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "ContactFkId" }, "CONTACT_FK_ID");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID1");

                    b.ToTable("employee_address_details", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeAdministrativeInformation", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ADMIN_ID");

                    b.Property<string>("Benefit")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("BENEFIT");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("SalaryId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("SALARY_ID");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("AdminId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID2");

                    b.ToTable("employee_administrative_information", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeContactDetail", b =>
                {
                    b.Property<int>("ContactPkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CONTACT_PK_ID");

                    b.Property<string>("ConNum")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CON_NUM");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("EmergencyConName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("EMERGENCY_CON_NAME");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("Relation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RELATION");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int")
                        .HasColumnName("TYPE_ID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("ContactPkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID3");

                    b.HasIndex(new[] { "TypeId" }, "TYPE_ID");

                    b.ToTable("employee_contact_details", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeEducationalDetail", b =>
                {
                    b.Property<int>("EducationalPkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EDUCATIONAL_PK_ID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Degree")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEGREE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("Institute")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("INSTITUTE");

                    b.Property<string>("Major")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MAJOR");

                    b.Property<string>("NameOfTheDegree")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("NAME_OF_THE_DEGREE");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<DateOnly?>("YearOfCompletion")
                        .HasColumnType("date")
                        .HasColumnName("YEAR_OF_COMPLETION");

                    b.HasKey("EducationalPkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID4");

                    b.ToTable("employee_educational_details", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeExperienceDetail", b =>
                {
                    b.Property<int>("ExpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EXP_ID");

                    b.Property<string>("CompanyName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("COMPANY_NAME");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("Designation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DESIGNATION");

                    b.Property<string>("Duration")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DURATION");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("END_DATE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("KeyRole")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("KEY_ROLE");

                    b.Property<string>("OtherInfo")
                        .HasColumnType("text")
                        .HasColumnName("OTHER_INFO");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("START_DATE");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("ExpId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID5");

                    b.ToTable("employee_experience_details", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeHrInfo", b =>
                {
                    b.Property<int>("HrInfoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("HR_INFO_ID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("HrGpLink")
                        .HasColumnType("text")
                        .HasColumnName("HR_GP_LINK");

                    b.Property<string>("HrGpName")
                        .HasColumnType("text")
                        .HasColumnName("HR_GP_NAME");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("HrInfoId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID6");

                    b.ToTable("employee_hr_info", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeInformation", b =>
                {
                    b.Property<int>("PkEmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_EMPLOYEE_ID");

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("AGE");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("BLOOD_GROUP");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("DATE_OF_BIRTH");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EMPLOYEE_ID");

                    b.Property<string>("FatherName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FATHER_NAME");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("GENDER");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("MaritalStatus")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("MARITAL_STATUS");

                    b.Property<string>("MobileNo")
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("MOBILE_NO");

                    b.Property<string>("PersonalMail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PERSONAL_MAIL");

                    b.Property<string>("Prefix")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("PREFIX");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("PkEmployeeId")
                        .HasName("PRIMARY");

                    b.ToTable("employee_information", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeJobInformation", b =>
                {
                    b.Property<int>("JobPkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JOB_PK_ID");

                    b.Property<string>("CompanyMail")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("COMPANY_MAIL");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<DateOnly?>("DateOfJoining")
                        .HasColumnType("date")
                        .HasColumnName("DATE_OF_JOINING");

                    b.Property<string>("Department")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("DEPARTMENT");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("JobTitleDesignation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("JOB_TITLE_DESIGNATION");

                    b.Property<string>("ReportingManager")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("REPORTING_MANAGER");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.Property<string>("WorkLocation")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("WORK_LOCATION");

                    b.HasKey("JobPkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID7");

                    b.ToTable("employee_job_information", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeNationalityDocument", b =>
                {
                    b.Property<int>("NatPkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("NAT_PK_ID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<string>("NationalityGpLink")
                        .HasColumnType("text")
                        .HasColumnName("NATIONALITY_GP_LINK");

                    b.Property<string>("NationalityGpName")
                        .HasColumnType("text")
                        .HasColumnName("NATIONALITY_GP_NAME");

                    b.Property<string>("NationalityGpNumber")
                        .HasColumnType("text")
                        .HasColumnName("NATIONALITY_GP_NUMBER");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("NatPkId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID8");

                    b.ToTable("employee_nationality_document", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeSupportDocument", b =>
                {
                    b.Property<int>("SupDocId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("SUP_DOC_ID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<string>("EduGrpLink")
                        .HasColumnType("text")
                        .HasColumnName("EDU_GRP_LINK");

                    b.Property<string>("EduGrpName")
                        .HasColumnType("text")
                        .HasColumnName("EDU_GRP_NAME");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("SupDocId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID9");

                    b.ToTable("employee_support_document", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmploymentStatusUpdate", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("STAT_ID");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("CREATED_BY");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("CREATED_DATE");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<DateOnly?>("LastWday")
                        .HasColumnType("date")
                        .HasColumnName("LAST_WDAY");

                    b.Property<string>("Rl")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("RL");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS");

                    b.Property<bool?>("StatusInd")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("STATUS_IND");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("UPDATED_BY");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime")
                        .HasColumnName("UPDATED_DATE");

                    b.HasKey("StatId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID10");

                    b.ToTable("employment_status_updates", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.UserInfo", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.Property<int?>("FkId")
                        .HasColumnType("int")
                        .HasColumnName("FK_ID");

                    b.Property<bool?>("Role")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("ROLE");

                    b.HasKey("UserId")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FkId" }, "FK_ID")
                        .HasDatabaseName("FK_ID11");

                    b.ToTable("user_info", (string)null);
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeAdditionalInfo", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeAdditionalInfos")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_additional_info_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeAddressDetail", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeContactDetail", "ContactFk")
                        .WithMany("EmployeeAddressDetails")
                        .HasForeignKey("ContactFkId")
                        .HasConstraintName("employee_address_details_ibfk_1");

                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeAddressDetails")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_address_details_ibfk_2");

                    b.Navigation("ContactFk");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeAdministrativeInformation", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeAdministrativeInformations")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_administrative_information_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeContactDetail", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeContactDetails")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_contact_details_ibfk_1");

                    b.HasOne("Workiy_360.EntityFramework.ContactType", "Type")
                        .WithMany("EmployeeContactDetails")
                        .HasForeignKey("TypeId")
                        .HasConstraintName("employee_contact_details_ibfk_2");

                    b.Navigation("Fk");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeEducationalDetail", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeEducationalDetails")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_educational_details_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeExperienceDetail", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeExperienceDetails")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_experience_details_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeHrInfo", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeHrInfos")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_hr_info_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeJobInformation", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeJobInformations")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_job_information_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeNationalityDocument", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeNationalityDocuments")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_nationality_document_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeSupportDocument", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmployeeSupportDocuments")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employee_support_document_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmploymentStatusUpdate", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("EmploymentStatusUpdates")
                        .HasForeignKey("FkId")
                        .HasConstraintName("employment_status_updates_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.UserInfo", b =>
                {
                    b.HasOne("Workiy_360.EntityFramework.EmployeeInformation", "Fk")
                        .WithMany("UserInfos")
                        .HasForeignKey("FkId")
                        .HasConstraintName("user_info_ibfk_1");

                    b.Navigation("Fk");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.ContactType", b =>
                {
                    b.Navigation("EmployeeContactDetails");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeContactDetail", b =>
                {
                    b.Navigation("EmployeeAddressDetails");
                });

            modelBuilder.Entity("Workiy_360.EntityFramework.EmployeeInformation", b =>
                {
                    b.Navigation("EmployeeAdditionalInfos");

                    b.Navigation("EmployeeAddressDetails");

                    b.Navigation("EmployeeAdministrativeInformations");

                    b.Navigation("EmployeeContactDetails");

                    b.Navigation("EmployeeEducationalDetails");

                    b.Navigation("EmployeeExperienceDetails");

                    b.Navigation("EmployeeHrInfos");

                    b.Navigation("EmployeeJobInformations");

                    b.Navigation("EmployeeNationalityDocuments");

                    b.Navigation("EmployeeSupportDocuments");

                    b.Navigation("EmploymentStatusUpdates");

                    b.Navigation("UserInfos");
                });
#pragma warning restore 612, 618
        }
    }
}
